from __future__ import annotations

from typing import Any, Protocol

from agent_task_fns._state import CheckResult, RepoInfo

class AgentTaskFns(Protocol):
    """Generated registry protocol for procedures loaded into ctx.fns."""

    def ask_ollama(self, ctx: AgentTaskCtx, prompt: str) -> str: ...
    def detect_project_checks(self, ctx: AgentTaskCtx) -> list[str]: ...
    def find_relevant_files(self, ctx: AgentTaskCtx, task: str) -> list[str]: ...
    def inspect_repo(self, ctx: AgentTaskCtx) -> RepoInfo: ...
    def propose_patch_plan(self, ctx: AgentTaskCtx) -> str: ...
    def read_files(self, ctx: AgentTaskCtx, files: list[str]) -> dict[str, str]: ...
    def render_next_actions(self, ctx: AgentTaskCtx) -> list[str]: ...
    def render_pr_description(self, ctx: AgentTaskCtx) -> str: ...
    def run_checks(self, ctx: AgentTaskCtx) -> CheckResult: ...
    def set_task(self, ctx: AgentTaskCtx, task: str) -> str: ...
    def summarize_checks(self, ctx: AgentTaskCtx, result: CheckResult) -> str: ...
    def system_start(self, ctx: AgentTaskCtx, task: str) -> str: ...


class AgentTaskCtx(Protocol):
    """Generated context protocol with app-specific ctx.fns typing."""

    fns: AgentTaskFns
    config: dict[str, Any]
    state: dict[str, Any]
    t: Any
