from __future__ import annotations

from typing import Any, Protocol

class AgentTaskFns(Protocol):
    """Generated registry protocol for procedures loaded into ctx.fns."""

    def find_relevant_files(self, ctx: AgentTaskCtx, task: str) -> list[str]: ...
    def inspect_repo(self, ctx: AgentTaskCtx) -> dict[str, list[str]]: ...
    def read_files(self, ctx: AgentTaskCtx, files: list[str]) -> dict[str, str]: ...
    def render_pr_description(self, ctx: AgentTaskCtx) -> str: ...
    def run_checks(self, ctx: AgentTaskCtx) -> 'dict[str, bool | int | float | str]': ...
    def set_task(self, ctx: AgentTaskCtx, task: str) -> str: ...
    def summarize_checks(self, ctx: AgentTaskCtx, result: 'dict[str, bool | int | float | str]') -> str: ...
    def system_start(self, ctx: AgentTaskCtx, task: str) -> str: ...


class AgentTaskCtx(Protocol):
    """Generated context protocol with app-specific ctx.fns typing."""

    fns: AgentTaskFns
    config: dict[str, Any]
    state: dict[str, Any]
    t: Any
