from __future__ import annotations

from typing import cast

from agent_task_fns._ctx_types import AgentTaskCtx


def render_pr_description(ctx: AgentTaskCtx) -> str:
    task = str(ctx.state.get("task", ""))
    relevant = cast(object, ctx.state.get("relevant_files", []))
    check_summary = str(ctx.state.get("check_summary", "not run"))
    llm_pr_description = str(ctx.state.get("llm_pr_description", ""))
    ollama_error = str(ctx.state.get("ollama_error", ""))
    files: list[str] = []
    if isinstance(relevant, list):
        relevant_items = cast(list[object], relevant)
        for item in relevant_items:
            if isinstance(item, str):
                files.append(item)
    lines = [
        "# Agent Task Report",
        "",
        "## Task",
        task,
        "",
        "## Relevant Files",
    ]
    if files:
        lines.extend(f"- `{file_name}`" for file_name in files)
    else:
        lines.append("- none found")
    lines.extend(
        [
            "",
            "## Checks",
            check_summary,
            "",
            "## Suggested PR Description",
            llm_pr_description or f"Implements or investigates: {task}",
            "",
            "This report was generated by the `agent_task_runtime` dogfood example.",
        ]
    )
    if ollama_error and not llm_pr_description:
        lines.extend(["", "## Local LLM", f"Ollama unavailable: {ollama_error}"])
    return "\n".join(lines)
